client_config_backend: file
client_config:
    client_id: 380928175445-rjuo75h932qd8l23fq698jb1953msahk.apps.googleusercontent.com
    client_secret: i6eJa-i2gIygt-ikU-gSJHj1

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials/drive_credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install